#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use FiveMin\Console\Commands\ParserCommand;

$app = new Application();
$app->add(new ParserCommand());
$app->run();